# -*- mode: ruby -*-
# vi: set ft=ruby :

show_gui     = true

vm_workgroup     = 'home'
vm_domain        = 'home.local'
vm_memsize       = "4096"
vm_cpus          = "1"
vm_cores_per_cpu = "4"

Vagrant.configure("2") do |config|

# Common Scripts for all VMs

  config.vm.boot_timeout = 600

  config.vm.synced_folder "../../scripts",    "/scripts"
  config.vm.synced_folder "../../localfiles", "/localfiles"

  config.vm.provision "shell", privileged: "true",
    path: "../../scripts/install-edge.bat"

  config.vm.provision "shell", privileged: "true",
    path: "../../scripts/configure-startup-shutdown.bat"

  # config.vm.provision "shell", privileged: "true",
  #   path: "../../scripts/configure-network.ps1",
  #   args: "-WorkGroupName '#{vm_workgroup}' -DNSDomain '#{vm_domain}' -SetInterfaceToPrivate",
  #   reboot: "true"

# Individual Server Config

  config.vm.define "scripting" do |this|
    this.vm.box = "ws2019"
    this.vm.hostname = "scripting"
    this.vm.provider "vmware_desktop" do |node|
      node.gui = show_gui
      node.vmx["memsize"]  = vm_memsize
      node.vmx["numvcpus"] = vm_cpus
      node.vmx["cpuid.coresPerSocket"] = vm_cores_per_cpu
      node.vmx['displayname'] = "scripting"
      node.vmx["ethernet0.pcislotnumber"] = "33"
      node.vmx["ethernet0.connectiontype"] = "nat" # "hostonly" "nat"
      node.vmx["ethernet0.virtualDev"] = "vmxnet3"
    end

    # this.vm.provision "shell", privileged: "true",
    #   inline: "Add-Content -Path 'c:/windows/system32/drivers/etc/hosts' -Value '127.0.0.1    app.local'"

  end

end
