# -*- mode: ruby -*-
# vi: set ft=ruby :

show_gui     = true

vm_workgroup     = 'home'
vm_domain        = 'home.local'
vm_memsize       = "4096"
vm_cpus          = "1"
vm_cores_per_cpu = "4"

Vagrant.configure("2") do |config|

# Common Scripts for all VMs

  config.vm.synced_folder "../scripts",    "/scripts"
  config.vm.synced_folder "../localfiles", "/localfiles"

  config.vm.provision "shell", privileged: "true",
    path: "../scripts/install-edge.bat"

  config.vm.provision "shell", privileged: "true",
    path: "../scripts/configure-startup.bat"

  #config.vm.provision "shell", privileged: "true",
  #  path: "../scripts/configure-network.ps1",
  #  args: "-WorkGroupName '#{vm_workgroup}' -DNSDomain '#{vm_domain}' -SetInterfaceToPrivate",
  #  reboot: "true"

# Individual VM Config

  config.vm.define "scripting" do |this|
    this.vm.box = "w10e"
    this.vm.hostname = "Win10"
    this.vm.provider "vmware_desktop" do |node|
      node.gui = show_gui
      node.vmx["memsize"]  = vm_memsize
      node.vmx["numvcpus"] = vm_cpus
      node.vmx["cpuid.coresPerSocket"] = vm_cores_per_cpu
      node.vmx['displayname'] = "Win10"
      node.vmx["ethernet0.pcislotnumber"] = "33"
      node.vmx["ethernet0.connectiontype"] = "nat"
      node.vmx["ethernet0.virtualDev"] = "vmxnet3"
    end

  end

end
